collections:
  authors:
    output: true
  
# to automatically add the layout to each post/author etc. without explicitly adding it
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"